apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# The target namespace where Argo CD controller is running
namespace: default

# Lists the resources Kustomize will bundle together
resources:
  - root-app.yaml

# Common metadata injected into all resources managed by this file
commonLabels:
  managed-by: gitops-bootstrap