apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-apps-manager
  namespace: default
spec:
  project: default
  source:
    repoURL: 'https://github.com/kuntrapakam/terraform-aws-helm-charts.git'
    targetRevision: HEAD
    path: apps # Points to the folder containing child manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default # Must be deployed into the Argo CD namespace
  syncPolicy:
    automated:
      prune: true # Deletes child apps if their files are removed from Git
      selfHeal: true
